config/routes.rb
Rails.application.routes.draw do

  devise_for :staffs
  resources :staffs, except: :show
  resources :card_types
  resources :discount_rates
  resources :partners
  resources :visits
  resources :members
  resources :categories
  resources :areas

  devise_scope :staff do
    get '/sign-in' => "devise/sessions#new", :as => :login
  end

  get '/generate_partner_login_credential', to: 'partners#generate_partner_login_credential', as: 'new_credential_for_partner'
  get '/reset_password', to: 'partners#reset_password', as: 'reset_password'

  get '/discount_rate', to: 'discount_rates#get_rate'

  get '/partners/:id/search', to: 'partners#search', as: 'partner_search'

  get '/staff/reset_password', to: 'staffs#reset_password', as: 'staff_reset_password'
  post '/staff_registration', to: 'staffs#create', as: 'create_staff'

  root to: 'application#home'
end

app/models/staff.rb
class Staff < ApplicationRecord

  belongs_to :partner, optional: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def partner
    Partner.find_by(staff_id: self.id)
  end

  def is_management_staff?
    self.management_staff == true
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :is_admin?

  def new
    @staff = Staff.new
  end

  def create
    @staff = Staff.new(staff_params)
    @staff.management_staff = true
    new_password = generate_new_password
    @staff.password = new_password

    respond_to do |format|
      if @staff.save
        format.html { redirect_to staffs_path, notice: "staff was successfully created. Password: #{new_password}" }
      else
        format.html { render :new }
      end
    end
  end

  def index
    @staffs = Staff.where('management_staff = true')
  end

  def destroy
    @staff = Staff.find(params[:id])
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def reset_password
    @staff = Staff.find(params[:id])
    new_password = generate_new_password
    @staff.password = new_password
    @staff.save

    respond_to do |format|
      format.html { redirect_to staffs_path, notice: "New password generated: #{new_password}" }
    end
  end

  private 
  def staff_params
    params.require(:staff).permit(:email, :first_name, :last_name, :phone_number)
  end

  def generate_new_password
    range = [*'0'..'9',*'A'..'Z',*'a'..'z']
    Array.new(8){ range.sample }.join
  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/index.html.erb
<h2>Staffs</h2>

<div id="staff-index-page">

  <div class="header-container">
    <%= link_to 'New Staff', new_staff_path, class: "btn btn-primary", class: "btn btn-primary" %>
  </div>

  <div id="staff-index-block" class="shadow-sm p-3 mb-5 rounded">

    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th scope="col">Staff ID</th>
          <th scope="col">Email</th>
          <th scope="col">Name</th>
          <th scope="col">Phone Number</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @staffs.each do |staff| %>
          <tr>
            <td><%= staff.id %></td>
            <td><%= staff.email %></td>
            <td><%= "#{staff.first_name} #{staff.last_name}" %></td>
            <td><%= staff.phone_number %></td>

            <td>
              <% if staff.admin? %>
                Admin Account
              <% else %>
                <%= link_to 'Reset Password', staff_reset_password_path(id: staff.id), data: { confirm: 'Are you sure to reset password?' }, class: "btn btn-danger btn-sm" %>
                <%= link_to 'Delete', staff, method: :delete, data: { confirm: 'Are you sure to delete this staff?' }, class: "btn btn-outline-danger btn-sm" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= form_for @staff, url: create_staff_path do |form| %>

  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :staff_email %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :staff_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :staff_last_name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, id: :staff_phone_number %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: "btn btn-primary" %>
  </div>
<% end %>