config/routes.rb
Rails.application.routes.draw do

  devise_for :staffs
  resources :staffs, except: :show
  resources :card_types
  resources :discount_rates
  resources :partners
  resources :visits
  resources :members
  resources :categories
  resources :areas

  devise_scope :staff do
    get '/sign-in' => "devise/sessions#new", :as => :login
  end

  get '/generate_partner_login_credential', to: 'partners#generate_partner_login_credential', as: 'new_credential_for_partner'
  get '/reset_password', to: 'partners#reset_password', as: 'reset_password'

  get '/discount_rate', to: 'discount_rates#get_rate'

  get '/partners/:id/search', to: 'partners#search', as: 'partner_search'

  get '/staff/reset_password', to: 'staffs#reset_password', as: 'staff_reset_password'
  post '/staff_registration', to: 'staffs#create', as: 'create_staff'

  root to: 'application#home'
end

app/models/partner.rb
class Partner < ApplicationRecord
  has_many :visits, :dependent => :delete_all
  has_many :discount_rates, :dependent => :delete_all
  belongs_to :staff, optional: true
  belongs_to :category, optional: true
  belongs_to :area, optional: true
  
  validates :name,  presence: true
  validate :category_area_combination

  def generate_staff_account
    if self.staff.nil?
      new_staff_email = "#{self.name.parameterize}"

      if unique_staff_email? new_staff_email
        new_staff_email = "#{new_staff_email}_#{SecureRandom.hex(2)}"
      end

      new_password = self.generate_new_password;
      self.staff = Staff.create(email: "#{new_staff_email}@#{ENV['HOST']}", password: new_password, password_confirmation: new_password)
      self.save

      return { staff: self.staff, password: new_password }
    end
  end

  def discount_rate_of_card_type(card_type_id)
    self.discount_rates.where(card_type_id: card_type_id).first
  end

  def has_discount_rate_of_card_type?(card_type_id)
    !self.discount_rates.where(card_type_id: card_type_id).empty?
  end

  def unique_staff_email? email
    !Staff.find_by(email: "#{email}@#{ENV['HOST']}").nil?
  end

  def generate_new_password
    range = [*'0'..'9',*'A'..'Z',*'a'..'z']
    Array.new(8){ range.sample }.join
  end

  def category_area_combination
    if self.category.present? && self.area.present?
      existing_combination_partners = Partner.where("category_id = #{self.category.id} AND area_id = #{self.area.id}")
      
      if existing_combination_partners.empty?
        return true
      end

      if existing_combination_partners.size == 1 && existing_combination_partners.include?(self)
        return true
      end

      self.errors.add(:base, "Category and area combination must be unique.")
      return false
    else
      return true
    end
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  include ApplicationHelper
  before_action :set_partner, only: [:show, :edit, :update, :destroy]
  before_action :is_admin_or_management_staff?, except: :search
  before_action :populate_unset_discount_rates
  before_action :generate_logo_url, only: [:show, :edit]

  # GET /partners
  # GET /partners.json
  def index
    @partners = Partner.all
    @partners = @partners.map do |partner|
      if partner.logo_key.present?
        partner.logo_url = get_signed_url(partner.logo_key)
      else
        partner.logo_url = ""
      end
      partner
    end
  end

  # GET /partners/1
  # GET /partners/1.json
  def show
    @card_types = CardType.order(id: :asc).all
  end

  def visits
    @partner_id = params[:id]
    render json: Partner.find(@partner_id).visits
  end

  # GET /partners/new
  def new
    @partner = Partner.new
    generate_s3_file_uploader_params
    @new_page = true
  end

  # GET /partners/1/edit
  def edit
    generate_s3_file_uploader_params
  end

  # POST /partners
  # POST /partners.json
  def create
    @partner = Partner.new(partner_params)

    respond_to do |format|
      if @partner.save
        format.html { redirect_to @partner, notice: 'Partner was successfully created.' }
        format.json { render :show, status: :created, location: @partner }
      else
        @new_page = true
        format.html { render :new }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partners/1
  # PATCH/PUT /partners/1.json
  def update
    respond_to do |format|
      if @partner.update(partner_params)
        format.html { redirect_to @partner, notice: 'Partner was successfully updated.' }
        format.json { render :show, status: :ok, location: @partner }
      else
        format.html { render :edit }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1
  # DELETE /partners/1.json
  def destroy

    if params[:password].present?
      if current_staff.valid_password? params[:password]
        @partner.destroy
        render json: {}, status: :ok and return
      end
    end

    render json: {message: "Invalid password"}, status: :unprocessable_entity and return
  end

  def generate_partner_login_credential
    @partner = Partner.find(params[:id])
    
    begin
    if @partner.staff.nil?
      new_staff = @partner.generate_staff_account
      
      redirect_to( partner_path(@partner), notice: "Login credential generated. Password: #{new_staff[:password]}" )
      return
    end
      
    rescue Exception => e
      redirect_to( partner_path(@partner), alert: "Error: #{e}" )
      return
    end

    redirect_to( partner_path(@partner), notice: "Login credential already exist" )
    return
  end

  def reset_password
    @partner = Partner.find(params[:id])
    new_password = @partner.generate_new_password
    @partner.staff.password = new_password
    @partner.staff.save

    respond_to do |format|
      format.html { redirect_to partner_path(@partner), notice: "New password generated: #{new_password}" }
    end
  end

  def search
    render :search
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner
      @partner = Partner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partner_params
      params.require(:partner).permit(:name, :category_id, :area_id, :logo_key)
    end

  def populate_unset_discount_rates
    Partner.all.each do |partner|
      CardType.all.each do |card_type|
        if partner.discount_rate_of_card_type(card_type.id).nil?
          partner.discount_rates.create(card_type_id: card_type.id, discount_rate: 0.2)
        end
      end
    end
  end

  def generate_logo_url
    if @partner.logo_key.present?
      @partner.logo_url = get_signed_url(@partner.logo_key)
    else
      @partner.logo_url = ""
    end
  end

  def generate_s3_file_uploader_params
    signer = Aws::S3::Presigner.new(client: S3_CLIENT)
    @file_key = "#{@partner.id}-#{SecureRandom.uuid}"
    @url = signer.presigned_url(
      :put_object,
      bucket: ENV['S3_BUCKET'],
      key: @file_key
    )
  end
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/partners/_form.html.erb
<%= form_with(model: partner, local: true) do |form| %>
  <% if partner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(partner.errors.count, "error") %> prohibited this partner from being saved:</h2>

      <ul>
      <% partner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :partner_name %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.order(:id), :id, :name, :include_blank => "Please select" %>
  </div>

  <div class="field">
    <%= form.label :area_id %>
    <%= form.collection_select :area_id, Area.order(:id), :id, :name, :include_blank => "Please select" %>
  </div>

  <%= yield :image_uploader %>

  <div class="actions">
    <%= form.submit 'Submit', class: "btn btn-primary" %>

    <% if !@new_page.present? %>
      <%= link_to 'Detail', @partner, class: "btn btn-secondary" %>
    <% end %>
  </div>
<% end %>

app/views/partners/edit.html.erb
<%= javascript_pack_tag 'image-uploader' %>

<h1>Editing Partner</h1>

<% content_for :image_uploader do %>
  <hr>
  <div class="logo-uploader-container">
    <h4>Logo</h4>
    <%= image_tag( @partner.logo_url, class: "logo_picture row") %>

    <%= content_tag :div,
      id: "image-uploader",
      data: {
        pre_sign_url: @url,
        file_key: @file_key,
        form_name: "logo_key",
        class_name: "partner"
      }.to_json do %>
    <% end %>
  </div>
  <hr>
<% end %>

<%= render 'form', partner: @partner %>

<p class="reminder-text">
  Reminder: <br/><br/>

  To update Partner logo, please upload the file with <b>Upload</b> button before submitting.
</p>

app/views/partners/index.html.erb
<div id="partner-index-page">

  <div class="header-container">
    <h2 class="display-5">Partners</h2>
    <%= link_to 'New Partner', new_partner_path, class: "btn btn-primary" %>
  </div>

  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Category</th>
        <th scope="col">Area</th>
        <th scope="col">Logo</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @partners.each do |partner| %>
        <tr>
          <td><%= partner.id %></td>
          <td><%= partner.name %></td>
          <td><%= partner.category.try(:name) || "N/A" %></td>
          <td><%= partner.area.try(:name) || "N/A" %></td>
          <td>
            <% if partner.logo_url.present? %>
              <%= image_tag( partner.logo_url, class: "logo_picture") %>
            <% else %>
              Not Available
            <% end %>
          </td>
          <td>
            <%= link_to 'Detail', partner, class: "btn btn-outline-info btn-sm" %>
            <%= link_to 'Edit', edit_partner_path(partner), class: "btn btn-outline-primary btn-sm" %>
            <button type="button" class="btn btn-outline-danger btn-sm" data-target="#deletion-confirmation-<%= partner.id %>" data-toggle="modal">Delete</button>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%# Deletion confirmation dialog %>
  <% @partners.each do |partner| %>
    <div class="modal fade" tabindex="-1" role="dialog" id="deletion-confirmation-<%= partner.id %>">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Delete Partner</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Please enter your password to confirm deletion of <b><%= partner.name %></b></p>
            <input type="password" class="form-control" placeholder="Password" name="<%= partner.id %>">
            <p id="deletion-message-<%= partner.id %>"></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
            <button type="button" class="btn btn-danger partner-deletion-button" name="<%= partner.id %>">Delete</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<script>
  $("input[type='password']").keypress(function(evt){
    
    var keycode = (evt.keyCode ? evt.keyCode : evt.which);
    if(keycode == '13'){
      const partnerID = evt.target.name;
      $(`button[name='${partnerID}']`).click();
    }
  });

  $(".partner-deletion-button").click((evt) => {
    const partnerID = evt.target.name;
    const adminPassword = $(`input[type='password'][name='${partnerID}']`).val();

    $.ajax({
      type: "DELETE",
      beforeSend: xhr => {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
      url: `/partners/${partnerID}`,
      data: { password: adminPassword },
      success: () => {
        $(`#deletion-message-${partnerID}`).attr("class","deletion-button success");
        $(`#deletion-message-${partnerID}`).text("Deletion success. Refreshing partner page ...");
        setTimeout(function() {
          location.reload();
        }, 500);
      },
      error: () => { 
        $(`#deletion-message-${partnerID}`).attr("class","deletion-button failure");
        $(`#deletion-message-${partnerID}`).text("Password is incorrect");
      }
    });
    
  });
</script>

app/views/partners/new.html.erb
<%= javascript_pack_tag 'image-uploader' %>

<h1>New Partner</h1>

<% content_for :image_uploader do %>
  <hr>
  <div class="logo-uploader-container">
    <h4>Logo</h4>

    <%= content_tag :div,
      id: "image-uploader",
      data: {
        pre_sign_url: @url,
        file_key: @file_key,
        form_name: "logo_key",
        class_name: "partner"
      }.to_json do %>
    <% end %>
  </div>
  <hr>
<% end %>

<%= render 'form', partner: @partner %>

app/views/partners/search.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= stylesheet_link_tag 'search' %>
<%= javascript_pack_tag 'search' %>

<%= content_tag :div,
  id: "partner-search",
  class: "row",
  data: {
    partner: @partner
  }.to_json do %>
<% end %>

app/views/partners/show.html.erb
<div id="partner-show-block">

  <h2>Partner Detail: #<%= @partner.id%> </h2>

  <div id="partner-info">
    <div class="row">
      <div class="col-4">
        <strong>Name:</strong>
      </div>
      <div class="col-8">
        <%= @partner.name %>
      </div>
    </div class="row">

    <div class="row">
      <div class="col-4">
        <strong>Category:</strong>
      </div>
      <div class="col-8">
        <%= @partner.category.try(:name) || "N/A" %>
      </div>
    </div class="row">

    <div class="row">
      <div class="col-4">
        <strong>Area:</strong>
      </div>
      <div class="col-8">
        <%= @partner.area.try(:name) || "N/A" %>
      </div>
    </div class="row">

    <div class="row">
      <div class="col-4">
        <strong>Logo:</strong>
      </div>
      <div class="col-8">
        <% if @partner.logo_url.present? %>
          <%= image_tag( @partner.logo_url, class: "logo_picture") %>
        <% else %>
          Not Available
        <% end %>
      </div>
    </div class="row">

    <%= link_to 'Edit', edit_partner_path(@partner), class: "btn btn-outline-primary" %>
  </div>

  <div class="info-block">
    <h3>Discount Rates</h3>

    <table class="table table-hover">
      <tr>
        <th>Card Type</th>
        <th>Discount Rate</th>
        <th colspan="3"></th>
      </tr>

      <% @card_types.each do |card_type| %>
        <% if @partner.has_discount_rate_of_card_type? card_type.id %>
          <tr>
            <td>
              <%= card_type.type_name %>
            </td>
            <td>
              <%= @partner.discount_rate_of_card_type(card_type.id).discount_rate*100 %>%
            </td>
            <td>
              <%= link_to 'Edit', edit_discount_rate_path(@partner.discount_rate_of_card_type(card_type.id)), class: "btn btn-sm btn-outline-primary" %>
              <%= link_to 'Reset', @partner.discount_rate_of_card_type(card_type.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>

  <div class="info-block">
    <h3>Login Credential</h3>

  <% if !@partner.staff.nil? %>
    <table class="table table-hover">
      <tr>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>

      <tr>
        <td><%= @partner.staff.email %></td>
        <td><%= link_to 'Reset password', reset_password_path(id: @partner.id), data: { confirm: 'Are you sure to reset their password?' }, class: "btn btn-primary" %></td>
      </tr>
    </table>
  <% else %>
    <%= link_to 'Generate login credential', new_credential_for_partner_path(id: @partner.id), class: "btn btn-primary big-button" %>
  <% end %>

  </div>
</div>