config/routes.rb
Rails.application.routes.draw do

  devise_for :staffs
  resources :staffs, except: :show
  resources :card_types
  resources :discount_rates
  resources :partners
  resources :visits
  resources :members
  resources :categories
  resources :areas

  devise_scope :staff do
    get '/sign-in' => "devise/sessions#new", :as => :login
  end

  get '/generate_partner_login_credential', to: 'partners#generate_partner_login_credential', as: 'new_credential_for_partner'
  get '/reset_password', to: 'partners#reset_password', as: 'reset_password'

  get '/discount_rate', to: 'discount_rates#get_rate'

  get '/partners/:id/search', to: 'partners#search', as: 'partner_search'

  get '/staff/reset_password', to: 'staffs#reset_password', as: 'staff_reset_password'
  post '/staff_registration', to: 'staffs#create', as: 'create_staff'

  root to: 'application#home'
end

app/models/area.rb
class Area < ApplicationRecord
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  before_action :is_admin_or_management_staff?

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to areas_url, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to areas_url, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :area_name %>
  </div>
  
  <div class="actions">
    <%= form.submit 'Submit', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

app/views/areas/index.html.erb
<h1>Areas</h1>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% Area.all.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td>
          <%= link_to 'Edit', edit_area_path(area), class: "btn btn-outline-primary btn-sm" %>
          <%= link_to 'Delete', area, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path, class: "btn btn-primary" %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

app/views/areas/show.html.erb
<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>